{% set name = "apache-airflow-providers-http" %}
{% set version = "4.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_http-{{ version }}.tar.gz
  sha256: 75b34ac8c342fc67584580e5356180e581ff52ed961ff055786cfc2cbd0a0029

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - aiohttp >=3.9.2
    - apache-airflow >=2.8.0
    - asgiref >=2.3.0
    - requests >=2.27.0,<3
    - requests-toolbelt >=0.4.0

test:
  imports:
    - airflow.providers.http
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-http for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/http/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-http/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
